# Generated by Django 3.2.4 on 2021-06-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=40)),
                ('actors', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('language', models.CharField(choices=[('EN', 'English'), ('HI', 'Hindi')], max_length=2)),
                ('poster', models.ImageField(upload_to='media/posters')),
            ],
        ),
    ]
